version: "3.8"

services:
  backend:
    build: . /backend
    ports:
      - 8080:8080
    environment:
      DB_URL=jdbc:mariadb://localhost:3306/project

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      volumes:
        - project:/data/db

volumes:
  project: